Add a max pending job option
AndresTanasijczuk/SlurmDagman pull request #3
Opened 2022-06-21 15:46 UTC by mdebony

Hello,
I've added an option to limit the job submission in function of the number of pending job.
I think this option could be useful to other people.

The option name is --max-jobs-pending with a default value of 500.

2022-06-23 07:40 UTC, AndresTanasijczuk requested changes

2022-06-23 07:40 UTC, AndresTanasijczuk commented on lib/SlurmDagman/process/worker.py
> +        num_nodes_running, num_nodes_pending, num_nodes_unknown = self.__monitor()
I suggest not to call `__monitor()` here again.
`__monitor()` is called in `__execute_dag()` before calling `__submit_ready_nodes()`. So you have `num_nodes_pending` already available and you can pass it as an argument to  `__submit_ready_nodes()`.

2022-06-23 08:47 UTC, AndresTanasijczuk requested changes

2022-06-23 08:47 UTC, AndresTanasijczuk commented on lib/SlurmDagman/config/defaults/common.py
> +DEFAULTS['DAGMAN']['max_jobs_pending'] = '500'
I suggest to set a smaller default value for `max_jobs_pending`.
The default for `max_jobs_queued` is 500, where queued corresponds to all transient job states (basically PENDING and RUNNING). Thus, the default for `max_jobs_pending` should be smaller than the default for `max_jobs_queued`.

2022-06-23 14:30 UTC, mdebony commented on lib/SlurmDagman/process/worker.py
> +        num_nodes_running, num_nodes_pending, num_nodes_unknown = self.__monitor()
Ok, I will make the modification and test it

2022-06-23 14:32 UTC, mdebony commented on lib/SlurmDagman/config/defaults/common.py
> +DEFAULTS['DAGMAN']['max_jobs_pending'] = '500'
I've set it to 500 to be sure to not modified the default behavior of the tool (as with only default value the max_jobs_queued will always be the limiting factor).
Is a value of 100 seem fine to you ?

2022-06-23 15:11 UTC, AndresTanasijczuk commented on lib/SlurmDagman/config/defaults/common.py
> +DEFAULTS['DAGMAN']['max_jobs_pending'] = '500'
I see. Then it is better to set it to 0 than to 500.

2022-06-23 17:04 UTC, merged

2022-06-24 10:24 UTC, AndresTanasijczuk commented
Thanks @mdebony for the contribution!